apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapp
  labels:
    app: samplewebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp
    spec:
      containers:
      - name: samplewebapp
        image: suren67/samplewebapp:tagversion
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: samplewebapp
spec:
  selector:
    app: samplewebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
