apiVersion: apps/v1
kind: Deployment
metadata:
name: samplewebapp
labels:
  app: samplewebapp
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: samplewebapp
      tier: samplewebapp
  spec:
    containers:
    - name: samplewebapp
      image: suren67/samplewebapp:tagversion
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: samplewebapp
labels:
  app: samplewebapp
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: samplewebapp
  tier: samplewebapp
type: LoadBalancer
